version: '3.8'

services:
  jenkins:
    build: ./jenkinsController
    container_name: jenkinsController
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - docker
    networks:
      - app-network

  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2377:2376"
    networks:
      - app-network

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  app-network:
    driver: bridge
